export const fruits = [
        'Apple',
        'Apricots',
        'Avocado',
        'Banana',
        'Blackberries',
        'Blackcurrant',
        'Blueberries',
        'Breadfruit',
        'Cantaloupe',
        'Carambola',
        'Cherimoya',
        'Cherries',
        'Clementine',
        'Coconut Meat',
        'Cranberries',
        'Custard-Apple',
        'DateFruit',
        'Durian',
        'Elderberries',
        'Feijoa',
        'Figs',
        'Gooseberries',
        'Grapefruit',
        'Grapes',
        'Guava',
        'Honeydew Melon',
        'Jackfruit',
        'Java-Plum',
        'Jujube Fruit',
        'Kiwifruit',
        'Kumquat',
        'Lemon',
        'lime',
        'Lime',
        'Longan',
        'Loquat',
        'Lychee',
        'Mandarin',
        'Mango',
        'Mangosteen',
        'Mulberries',
        'Nectarine',
        'Olives',
        'Orange',
        'Papaya',
        'PassionFruit',
        'Peaches',
        'Pear',
        'Persimmon',
        'Pineapple'
    ]
  